### ISSUE TITLE
Can you update an Applesoft file on a .DSK from a local .BAS.ASC file?

### ISSUE THREAD

**Issue by philgoetz** [paleotronic/dskalyzer#7]
I did this:
```
mount "TEST DISK"
extract "TEST FILE"   <-- an Applesoft file
<edited the extracted local .BAS.ASC file>
put "TEST FILE"
unmount
```

and then re-opened the DSK file in Applewin, an Apple 2 emulator. The changes I made had not been written to the DSK file.

**Comment by philgoetz** [comment]
My problem is probably that I wasn't writing to the .BAS file; I was only writing to the .BAS.ASC file.
But I have no way to edit the .BAS file.
Is there a way to write out a local copy of the proper .BAS file corresponding to my locally-edited copy of it, so that I can edit an Applesoft file locally and update it on the .DSK image?

**Comment by retrocomputist** [comment]
You should be able to accomplish this with diskM8 https://github.com/paleotronic/diskm8
